version: '3.8'
services:
  service-discovery:
    build: ./service-discovery
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery:8761/eureka
      - JWT_SECRET=UmaSenhaLongaParaGerarHash
    depends_on:
      - service-discovery

  auth-service:
    build: ./auth-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:authdb
    depends_on:
      - service-discovery

  contas-service:
    build: ./contas-service
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:contasdb
    depends_on:
      - service-discovery